### ISSUE TITLE
执行go mod tidy的时候，提示go-ntlm库找不到，应该用哪个进行替代？

### ISSUE THREAD

**Issue by kisscelia** [Runner-Go-Team/RunnerGo-engine-open#1]
fatal: repository 'https://github.com/ThomsonReutersEikon/go-ntlm/' not found

**Comment by kisscelia** [comment]
感觉可以用这个替代
github.com/Azure/go-ntlmssp

**Comment by xiwunongyue** [comment]
github.com/ThomsonReutersEikon/go-ntlm/ntlm

**Comment by yx071507080826** [comment]
github.com/vadimi/go-ntlm/ntlm

实测这个可以

**Comment by kisscelia** [comment]
closed，谢谢您。
